using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Emlang.CodeGen;

/// <summary>
/// Emits the Decider's exhaustive Evolve/Decide switch skeletons: one switch arm plus one
/// private static partial declaration per spec e:/c:, in spec order, no default arm.
/// The case BODIES (the residue: scoring, selection, folding) live in the handwritten
/// Decider.Impl.cs — a new e:/c: in the spec is a CS8795 compile error until a human
/// (or agent) writes the body.
/// </summary>
public static class DeciderEmitter
{
    public static string Emit(EmitTarget target, IReadOnlyList<SpecElement> elements)
    {
        var events = elements.Where(e => e.Kind == 'e').ToList();
        var commands = elements.Where(e => e.Kind == 'c').ToList();
        var (state, context, eventUnion, commandUnion) =
            (target.StateType, target.ContextType, target.EventUnion, target.CommandUnion);

        var sb = new StringBuilder();
        sb.AppendLine($"// <auto-generated/> Generated by Emlang.Generators from {target.SpecFile}. Do not edit.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine($"namespace {target.Namespace};");
        sb.AppendLine();
        sb.AppendLine("public static partial class Decider");
        sb.AppendLine("{");
        sb.AppendLine($"    public static {state} Evolve({state} state, {eventUnion} @event) =>");
        sb.AppendLine("        @event switch");
        sb.AppendLine("        {");
        foreach (var e in events)
            sb.AppendLine($"            {e.Name} e => Evolve{e.Name}(state, e),");
        sb.AppendLine("        };");
        sb.AppendLine();
        sb.AppendLine($"    public static Result<{eventUnion}[]> Decide({state} state, {commandUnion} command, {context} context) =>");
        sb.AppendLine("        command switch");
        sb.AppendLine("        {");
        foreach (var c in commands)
            sb.AppendLine($"            {c.Name} c => Decide{c.Name}(state, c, context),");
        sb.AppendLine("        };");
        sb.AppendLine();
        foreach (var e in events)
            sb.AppendLine($"    private static partial {state} Evolve{e.Name}({state} state, {e.Name} e);");
        sb.AppendLine();
        foreach (var c in commands)
            sb.AppendLine($"    private static partial Result<{eventUnion}[]> Decide{c.Name}({state} state, {c.Name} command, {context} context);");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
