using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Emlang.CodeGen;

/// <summary>
/// Emits one stratum-1 surface file (Commands / Events / Errors) as C# text from the
/// spec elements of one kind: positional records in spec order, the closed union last.
/// Correctness proof: the emitted text must round-trip through SurfaceComparer with
/// zero divergences against the same spec (SurfaceEmitterTests).
/// </summary>
public static class SurfaceEmitter
{
    public static string Emit(EmitTarget target, IReadOnlyList<SpecElement> elements, char kind)
    {
        var own = elements.Where(e => e.Kind == kind).ToList();
        var union = kind == 'c' ? target.CommandUnion
            : kind == 'e' ? target.EventUnion
            : target.ErrorUnion;

        var sb = new StringBuilder();
        sb.AppendLine($"// <auto-generated/> Generated by Emlang.Generators from {target.SpecFile}. Do not edit.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine($"namespace {target.Namespace};");
        sb.AppendLine();
        foreach (var element in own)
            sb.AppendLine($"public record {element.Name}{Parameters(element)};");
        sb.AppendLine();
        sb.AppendLine($"public union {union}({string.Join(", ", own.Select(e => e.Name))});");
        return sb.ToString();
    }

    /// <summary>Rule: no props = parameterless marker record (the x: shape).</summary>
    private static string Parameters(SpecElement element) =>
        element.Props.Count == 0
            ? string.Empty
            : "(" + string.Join(", ", element.Props.Select(p => $"{p.Type} {p.Name}")) + ")";
}
