using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Emlang.CodeGen;

/// <summary>
/// Emits one SpecTests.g.cs per game: an xUnit class generated from the spec's `tests:`
/// sections. Three shapes, classified per test:
///   GWT decide      when: present            -> Decider.Decide, pin events | error
///   GT fold         no when, then State / X  -> Decider.Fold, pin state
///   GT projection   no when, then Screen|Todo -> Projections.X(Decider.Fold), pin view
/// Values are typed by the spec's own step/view prop declarations; bare words become
/// Fixtures.* references (a missing fixture is a CS0117 — the compiler is the oracle).
/// Union case checks use CONCRETE `is` patterns only (the union runtime-type trap:
/// a generic `is T` compiles to isinst and never matches a union value).
/// </summary>
public static class TestsEmitter
{
    /// <summary>The spec pair every emitter needs, bundled so it travels as one argument.</summary>
    private sealed record Spec(EmitTarget Target, IReadOnlyList<SpecElement> Elements);

    /// <summary>In tests mode the generator passes the TESTS project's RootNamespace as
    /// target.Namespace — enclosing-namespace lookup resolves the domain types from there.</summary>
    public static string Emit(
        EmitTarget target, IReadOnlyList<SpecElement> elements, IReadOnlyList<SpecTest> tests)
    {
        var spec = new Spec(target, elements);
        var sb = new StringBuilder();
        sb.AppendLine($"// <auto-generated/> Generated by Emlang.Generators from {target.SpecFile}. Do not edit.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using AwesomeAssertions;");
        sb.AppendLine("using Xunit;");
        sb.AppendLine();
        sb.AppendLine($"namespace {target.Namespace};");
        sb.AppendLine();
        sb.AppendLine("public class SpecTests");
        sb.AppendLine("{");
        string? slice = null;
        var first = true;
        foreach (var test in tests)
        {
            if (!first)
                sb.AppendLine();
            first = false;
            if (test.Slice != slice)
            {
                slice = test.Slice;
                sb.AppendLine($"    // --- {slice} ---");
                sb.AppendLine();
            }
            EmitTest(sb, spec, test);
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitTest(StringBuilder sb, Spec spec, SpecTest test)
    {
        sb.AppendLine($"    [Fact(DisplayName = {Quote(test.Name)})]");
        sb.AppendLine($"    public void {MethodName(test.Name)}()");
        sb.AppendLine("    {");
        var body = new StringBuilder();
        try
        {
            EmitBody(body, spec, test);
            sb.Append(body);
        }
        catch (SpecTestException failure)
        {
            sb.AppendLine($"        // emlang: {failure.Message}");
            sb.AppendLine($"        Assert.Fail({Quote($"spec test '{test.Name}': {failure.Message}")});");
        }
        sb.AppendLine("    }");
    }

    private static void EmitBody(StringBuilder sb, Spec spec, SpecTest test)
    {
        if (test.When is { } when)
            EmitDecideGwt(sb, spec, test, when);
        else if (test.Then.Count == 1 && test.Then[0] is { Kind: 'v' } view)
        {
            if (view.Lane == "State")
                EmitFoldGt(sb, spec, test, view);
            else
                EmitProjectionGt(sb, spec, test, view);
        }
        else
            throw new SpecTestException(
                $"unclassifiable test (line {test.Line}): no when: and then: is not a single view");
    }

    // --- GWT decide ----------------------------------------------------------

    private static void EmitDecideGwt(StringBuilder sb, Spec spec, SpecTest test, TestStep when)
    {
        EmitGiven(sb, spec, test);
        sb.AppendLine($"        var result = Decider.Decide(given, {Construct(spec.Elements, when)}, Fixtures.Context);");
        sb.AppendLine();

        if (test.Then.Count == 1 && test.Then[0].Kind == 'x')
            EmitThenError(sb, test.Then[0].Name);
        else
            EmitThenEvents(sb, spec, test);
    }

    /// <summary>The given-arrange: a State view pins Initial `with` props, no given stays
    /// Initial, and a list of events folds.</summary>
    private static void EmitGiven(StringBuilder sb, Spec spec, SpecTest test)
    {
        if (test.Given.Count == 1 && test.Given[0] is { Kind: 'v', Lane: "State" } state)
        {
            var element = View(spec.Elements, state);
            sb.AppendLine($"        var given = {spec.Target.StateType}.Initial with");
            sb.AppendLine("        {");
            sb.AppendLine(string.Join(",\n", state.Props.Select(p =>
                $"            {p.Name} = {Value(Declared(element, p), p.Value)}")));
            sb.AppendLine("        };");
        }
        else if (test.Given.Count == 0)
            sb.AppendLine($"        var given = {spec.Target.StateType}.Initial;");
        else
        {
            sb.AppendLine($"        var given = Decider.Fold(new {spec.Target.EventUnion}[]");
            sb.AppendLine("        {");
            foreach (var step in test.Given)
                sb.AppendLine($"            {Construct(spec.Elements, step)},");
            sb.AppendLine("        });");
        }
    }

    private static void EmitThenError(StringBuilder sb, string error)
    {
        sb.AppendLine("        if (result is not Err err)");
        sb.AppendLine("        {");
        sb.AppendLine($"            Assert.Fail(\"expected Err ({error}), got Ok (events)\");");
        sb.AppendLine("            return;");
        sb.AppendLine("        }");
        sb.AppendLine($"        (err.Error is {error}).Should().BeTrue(\"expected {error}\");");
    }

    private static void EmitThenEvents(StringBuilder sb, Spec spec, SpecTest test)
    {
        sb.AppendLine($"        if (result is not Ok<{spec.Target.EventUnion}[]> ok)");
        sb.AppendLine("        {");
        sb.AppendLine("            Assert.Fail(\"expected Ok (events), got Err\");");
        sb.AppendLine("            return;");
        sb.AppendLine("        }");
        sb.AppendLine("        var events = ok.Value;");

        // Group then-events by concrete type: collect via concrete `is` (the union trap),
        // pin by ordinal within the type.
        foreach (var group in test.Then.GroupBy(step => step.Name))
        {
            var local = CamelCase(group.Key);
            sb.AppendLine();
            sb.AppendLine($"        var {local} = new List<{group.Key}>();");
            sb.AppendLine("        foreach (var e in events)");
            sb.AppendLine($"            if (e is {group.Key} match)");
            sb.AppendLine($"                {local}.Add(match);");
            sb.AppendLine($"        {local}.Should().HaveCount({group.Count()});");
            var ordinal = 0;
            foreach (var step in group)
                EmitPin(sb, $"{local}[{ordinal++}]", Element(spec.Elements, 'e', step.Name, step.Line), step);
        }
    }

    // --- GT fold / projection --------------------------------------------------

    private static void EmitFoldGt(StringBuilder sb, Spec spec, SpecTest test, TestStep view)
    {
        sb.AppendLine($"        var state = Decider.Fold(new {spec.Target.EventUnion}[]");
        sb.AppendLine("        {");
        foreach (var step in test.Given)
            sb.AppendLine($"            {Construct(spec.Elements, step)},");
        sb.AppendLine("        });");
        sb.AppendLine();
        EmitPin(sb, "state", View(spec.Elements, view), view);
    }

    private static void EmitProjectionGt(StringBuilder sb, Spec spec, SpecTest test, TestStep view)
    {
        sb.AppendLine($"        var view = Projections.{ProjectionMethod(view.Name)}(Decider.Fold(new {spec.Target.EventUnion}[]");
        sb.AppendLine("        {");
        foreach (var step in test.Given)
            sb.AppendLine($"            {Construct(spec.Elements, step)},");
        sb.AppendLine("        }));");
        sb.AppendLine();
        EmitPin(sb, "view", View(spec.Elements, view), view);
    }

    /// <summary>
    /// Pin a then-value: anonymous-type subset equivalence (proven in-repo), always with
    /// strict ordering. `minted` props are excluded from the pin and asserted by presence
    /// (deterministic clock, real Guid.NewGuid — minted ids cannot be equality-pinned).
    /// </summary>
    private static void EmitPin(StringBuilder sb, string target, SpecElement element, TestStep step)
    {
        var minted = new List<SpecProp>();
        var members = new List<string>();
        foreach (var prop in step.Props)
        {
            var declared = Declared(element, prop);
            if (prop.Value is ScalarValue { Raw: "minted" })
                minted.Add(declared);
            else
                members.Add($"            {prop.Name} = {Value(declared, prop.Value)}");
        }
        if (members.Count > 0)
        {
            sb.AppendLine($"        {target}.Should().BeEquivalentTo(new");
            sb.AppendLine("        {");
            sb.AppendLine(string.Join(",\n", members));
            sb.AppendLine("        }, o => o.WithStrictOrdering());");
        }
        foreach (var prop in minted)
            sb.AppendLine($"        {target}.{prop.Name}.Should().NotBe(default({prop.Type}));");
    }

    // --- Value materialization ---------------------------------------------------

    /// <summary>Positional construction: declared props in order, missing ones default!
    /// (decider-true — the spec omits what the code under test never reads).</summary>
    private static string Construct(IReadOnlyList<SpecElement> elements, TestStep step)
    {
        var element = Element(elements, step.Kind, step.Name, step.Line);
        foreach (var prop in step.Props)
            Declared(element, prop); // undeclared prop -> diagnostic
        var args = element.Props.Select(declared =>
            step.Props.FirstOrDefault(p => p.Name == declared.Name) is { } given
                ? Value(declared, given.Value)
                : "default!");
        return $"new {step.Name}({string.Join(", ", args)})";
    }

    private static string Value(SpecProp declared, TestValue value) => value switch
    {
        ScalarValue { Raw: "minted" } =>
            throw new SpecTestException($"'minted' on {declared.Name} is only valid in a then: pin"),
        ScalarValue scalar => Scalar(declared.Type, declared.IsEnum, scalar.Raw),
        ListValue list => ListLiteral(declared, list),
        _ => throw new SpecTestException(
            $"prop '{declared.Name}' has an inline map value — replace it with a fixture reference"),
    };

    /// <summary>The general value-materialization rules (the tests-side sibling of
    /// SpecModel.MapType — keep this table SMALL, every row is a counted rule).</summary>
    public static string Scalar(string type, bool isEnum, string raw) => type switch
    {
        "string" => Quote(raw),
        "int" or "bool" => raw,
        "int?" => $"(int?){raw}", // raw "null" yields "(int?)null" — same emission either way
        "decimal" => raw + "m",
        "byte" => $"(byte){raw}",
        _ when isEnum => $"{type}.{SpecModel.PascalCase(raw)}",
        _ => $"Fixtures.{SpecModel.PascalCase(raw)}",
    };

    private static string ListLiteral(SpecProp declared, ListValue list)
    {
        var elementType = ElementType(declared.Type)
            ?? throw new SpecTestException($"prop '{declared.Name}' is a list but its type is {declared.Type}");
        var items = list.Items.Select(item => item switch
        {
            ScalarValue scalar => Scalar(elementType, declared.IsEnum, scalar.Raw),
            _ => throw new SpecTestException(
                $"prop '{declared.Name}' nests a list/map inside a list — replace rows with fixture references"),
        }).ToList();
        return items.Count == 0
            ? $"new {elementType}[] {{ }}"
            : $"new {elementType}[] {{ {string.Join(", ", items)} }}";
    }

    private static string? ElementType(string type) =>
        type.StartsWith("IReadOnlyList<", StringComparison.Ordinal) && type.EndsWith(">", StringComparison.Ordinal)
            ? type.Substring("IReadOnlyList<".Length, type.Length - "IReadOnlyList<".Length - 1)
            : null;

    // --- Lookups & names ---------------------------------------------------------

    private static SpecElement Element(IReadOnlyList<SpecElement> elements, char kind, string name, int line) =>
        elements.FirstOrDefault(e => e.Kind == kind && e.Name == name)
            ?? throw new SpecTestException($"no {kind}: element named {name} (spec line {line})");

    private static SpecElement View(IReadOnlyList<SpecElement> elements, TestStep step) =>
        elements.FirstOrDefault(e => e.Kind == 'v' && e.Lane == step.Lane && e.Name == step.Name)
            ?? throw new SpecTestException($"no v: element named {step.Lane} / {step.Name} (spec line {step.Line})");

    private static SpecProp Declared(SpecElement element, TestProp prop) =>
        element.Props.FirstOrDefault(d => d.Name == prop.Name)
            ?? throw new SpecTestException(
                $"prop '{prop.Name}' (spec line {prop.Line}) is not declared on {element.Name}");

    /// <summary>Rule: non-alphanumeric runs collapse to one '_' — the hand-written naming.</summary>
    public static string MethodName(string name)
    {
        var sb = new StringBuilder(name.Length);
        var pendingSeparator = false;
        foreach (var ch in name)
        {
            if (!char.IsLetterOrDigit(ch))
            {
                pendingSeparator = true;
                continue;
            }
            if (pendingSeparator && sb.Length > 0)
                sb.Append('_');
            pendingSeparator = false;
            sb.Append(ch);
        }
        return sb.Length > 0 && char.IsDigit(sb[0]) ? "_" + sb : sb.ToString();
    }

    /// <summary>Rule: lane-stripped view names word-PascalCase into projection methods
    /// ("Round scores" -> Projections.RoundScores, "Todo / Game progress" -> Projections.GameProgress).</summary>
    public static string ProjectionMethod(string viewName) =>
        string.Concat(viewName.Split(' ').Select(SpecModel.PascalCase));

    private static string CamelCase(string name) =>
        name.Length == 0 ? name : char.ToLowerInvariant(name[0]) + name.Substring(1);

    private static string Quote(string text) =>
        "\"" + text.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";

    /// <summary>A spec-shape problem: surfaces as ONE failing generated test with the
    /// message, never as a generator crash.</summary>
    private sealed class SpecTestException : Exception
    {
        public SpecTestException(string message) : base(message) { }
    }
}
