using System.Text.RegularExpressions;
using AwesomeAssertions;
using Emlang.CodeGen;
using Xunit;

namespace Emlang.Tests;

/// <summary>
/// The skeleton emitter's gate: per spec, the emitted text carries exactly one switch arm
/// AND one private static partial declaration per spec e:/c: — so a new spec element lands
/// as a CS8795 seam in the consumer, never a silently missing arm.
/// </summary>
public class DeciderEmitterTests
{
    private static void EmitsOneArmAndOnePartialPerSpecElement(EmitTarget target)
    {
        var elements = SpecModel.Parse(Fixture.Spec(target));

        var text = DeciderEmitter.Emit(target, elements);

        text.Should().StartWith("// <auto-generated/>");
        text.Should().Contain($"namespace {target.Namespace};");
        text.Should().Contain("public static partial class Decider");
        text.Should().NotContain("_ =>", "exhaustive union switches have no default arm");

        foreach (var e in elements.Where(x => x.Kind == 'e'))
        {
            Regex.Matches(text, Regex.Escape($"{e.Name} e => Evolve{e.Name}(state, e),")).Should().HaveCount(1);
            Regex.Matches(text, Regex.Escape(
                $"private static partial {target.StateType} Evolve{e.Name}({target.StateType} state, {e.Name} e);"))
                .Should().HaveCount(1);
        }

        foreach (var c in elements.Where(x => x.Kind == 'c'))
        {
            Regex.Matches(text, Regex.Escape($"{c.Name} c => Decide{c.Name}(state, c, context),")).Should().HaveCount(1);
            Regex.Matches(text, Regex.Escape(
                $"private static partial Result<{target.EventUnion}[]> Decide{c.Name}({target.StateType} state, {c.Name} command, {target.ContextType} context);"))
                .Should().HaveCount(1);
        }
    }

    [Fact]
    public void MerEllerMindre_skeleton_has_one_arm_and_one_partial_per_spec_element() =>
        EmitsOneArmAndOnePartialPerSpecElement(Fixture.MerEllerMindre);

    [Fact]
    public void Blindbudet_skeleton_has_one_arm_and_one_partial_per_spec_element() =>
        EmitsOneArmAndOnePartialPerSpecElement(Fixture.Blindbudet);

    [Fact]
    public void TankTillTusen_skeleton_has_one_arm_and_one_partial_per_spec_element() =>
        EmitsOneArmAndOnePartialPerSpecElement(Fixture.TankTillTusen);
}
