using AwesomeAssertions;
using Emlang.CodeGen;
using Xunit;

namespace Emlang.Tests;

/// <summary>
/// The emitter's correctness proof: feed the emitted text back through the SurfaceComparer
/// against the spec it was emitted from — zero divergences.
/// </summary>
public class SurfaceEmitterTests
{
    private static void EmittedSurfaceRoundTrips(EmitTarget target)
    {
        var spec = Fixture.Spec(target);
        var elements = SpecModel.Parse(spec);

        SurfaceComparer.Compare(target, spec,
                SurfaceEmitter.Emit(target, elements, 'c'),
                SurfaceEmitter.Emit(target, elements, 'e'),
                SurfaceEmitter.Emit(target, elements, 'x'))
            .Should().BeEmpty("the emitted surface must match the spec it was emitted from");
    }

    [Fact]
    public void MerEllerMindre_emitted_surface_round_trips_through_the_comparer() =>
        EmittedSurfaceRoundTrips(Fixture.MerEllerMindre);

    [Fact]
    public void Blindbudet_emitted_surface_round_trips_through_the_comparer() =>
        EmittedSurfaceRoundTrips(Fixture.Blindbudet);

    [Fact]
    public void TankTillTusen_emitted_surface_round_trips_through_the_comparer() =>
        EmittedSurfaceRoundTrips(Fixture.TankTillTusen);

    [Fact]
    public void Blindbudet_commands_emit_known_records_and_the_closed_union()
    {
        var spec = Fixture.Spec(Fixture.Blindbudet);

        var text = SurfaceEmitter.Emit(Fixture.Blindbudet, SpecModel.Parse(spec), 'c');

        text.Should().StartWith("// <auto-generated/>");
        text.Should().Contain("namespace Blindbudet.Domain;");
        text.Should().Contain("public record PlaceBid(Guid GameId, Guid PlayerId, int LotIndex, decimal Amount);");
        text.Should().Contain("public union AuctionCommand(");
    }

    [Fact]
    public void Errors_emit_parameterless_marker_records()
    {
        var spec = Fixture.Spec(Fixture.Blindbudet);

        var text = SurfaceEmitter.Emit(Fixture.Blindbudet, SpecModel.Parse(spec), 'x');

        text.Should().Contain("public record AuctionNotFound;");
        text.Should().Contain("public union AuctionError(");
    }
}
