using AwesomeAssertions;
using Emlang.CodeGen;
using Xunit;

namespace Emlang.Tests;

/// <summary>
/// The tests-stratum rules: value materialization one by one (each a counted rule, like
/// SpecModelTests), content spot-checks on the emitted tank text, and the coverage
/// invariant — every spec test becomes exactly one [Fact], all three games.
/// </summary>
public class TestsEmitterTests
{
    [Theory]
    [InlineData("string", false, "Martin", "\"Martin\"")]
    [InlineData("int", false, "0", "0")]
    [InlineData("bool", false, "true", "true")]
    [InlineData("int?", false, "null", "(int?)null")]
    [InlineData("int?", false, "20", "(int?)20")]
    [InlineData("decimal", false, "12.5", "12.5m")]
    [InlineData("byte", false, "42", "(byte)42")]
    [InlineData("Difficulty", true, "klassisk", "Difficulty.Klassisk")]
    [InlineData("Guid", false, "gameId", "Fixtures.GameId")]
    [InlineData("Solution", false, "solHit", "Fixtures.SolHit")]
    public void Scalar_materializes_by_the_declared_type(string type, bool isEnum, string raw, string expected) =>
        TestsEmitter.Scalar(type, isEnum, raw).Should().Be(expected);

    [Theory]
    [InlineData("game can be created", "game_can_be_created")]
    [InlineData("current puzzle presented with tal, mål and progress", "current_puzzle_presented_with_tal_mål_and_progress")]
    [InlineData("1 leads", "_1_leads")]
    public void Method_names_collapse_non_alphanumeric_runs(string name, string expected) =>
        TestsEmitter.MethodName(name).Should().Be(expected);

    [Theory]
    [InlineData("Roster", "Roster")]
    [InlineData("Round scores", "RoundScores")]
    [InlineData("Outstanding solutions", "OutstandingSolutions")]
    public void Projection_methods_word_pascal_case_the_view_name(string view, string expected) =>
        TestsEmitter.ProjectionMethod(view).Should().Be(expected);

    /// <summary>In tests mode the generator passes the tests project's RootNamespace —
    /// mirrored here by suffixing .Tests onto the domain namespace.</summary>
    private static string Emitted(EmitTarget target)
    {
        var yaml = Fixture.Spec(target);
        var testsTarget = target with { Namespace = target.Namespace + ".Tests" };
        return TestsEmitter.Emit(testsTarget, SpecModel.Parse(yaml), TestModel.Parse(yaml));
    }

    [Fact]
    public void Tank_emits_the_expected_shapes()
    {
        var text = Emitted(Fixture.TankTillTusen);

        text.Should().StartWith("// <auto-generated/>");
        text.Should().Contain("namespace TankTillTusen.Domain.Tests;");
        text.Should().Contain("public class SpecTests");
        text.Should().Contain("public void game_can_be_created()");
        text.Should().Contain("TankState.Initial with");                       // given State view
        text.Should().Contain("Difficulty.Klassisk");                          // enum note
        text.Should().Contain("Fixtures.SolHit");                              // fixture ref
        text.Should().Contain(".Should().NotBe(default(Guid));");              // minted pin
        text.Should().Contain("Projections.Roster(Decider.Fold(new TankEvent[]"); // projection GT
        text.Should().Contain("(err.Error is GameNotFound).Should().BeTrue");  // error then
        text.Should().Contain("if (result is not Ok<TankEvent[]> ok)");        // concrete union check
        text.Should().Contain("o => o.WithStrictOrdering()");
    }

    [Fact]
    public void Tank_emits_no_rejected_tests() =>
        Emitted(Fixture.TankTillTusen).Should().NotContain("// emlang:",
            "the normalized tank spec must map cleanly");

    private static void EveryTestEmitsExactlyOneFact(EmitTarget target)
    {
        var yaml = Fixture.Spec(target);
        var tests = TestModel.Parse(yaml);
        var text = TestsEmitter.Emit(target, SpecModel.Parse(yaml), tests);

        tests.Should().NotBeEmpty();
        foreach (var test in tests)
            Count(text, $"[Fact(DisplayName = \"{test.Name}\")]").Should().Be(1, "test '{0}'", test.Name);
        Count(text, "[Fact(").Should().Be(tests.Count);
    }

    private static int Count(string text, string token)
    {
        var count = 0;
        for (var i = text.IndexOf(token, StringComparison.Ordinal);
             i >= 0;
             i = text.IndexOf(token, i + 1, StringComparison.Ordinal))
            count++;
        return count;
    }

    [Fact]
    public void MerEllerMindre_every_spec_test_emits_exactly_one_fact() =>
        EveryTestEmitsExactlyOneFact(Fixture.MerEllerMindre);

    [Fact]
    public void Blindbudet_every_spec_test_emits_exactly_one_fact() =>
        EveryTestEmitsExactlyOneFact(Fixture.Blindbudet);

    [Fact]
    public void TankTillTusen_every_spec_test_emits_exactly_one_fact() =>
        EveryTestEmitsExactlyOneFact(Fixture.TankTillTusen);
}
