<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>RequestSample</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Xmlang" Version="0.6.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Specs/*.yaml" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
